/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAnalysisCard: typeof import('./src/components/reader/AiAnalysisCard.vue')['default']
    AnnotationListSheet: typeof import('./src/components/AnnotationListSheet.vue')['default']
    AnnotationNoteSheet: typeof import('./src/components/reader/AnnotationNoteSheet.vue')['default']
    ArticleCell: typeof import('./src/components/ArticleCell.vue')['default']
    ReaderAiSheet: typeof import('./src/components/ReaderAiSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionToolbar: typeof import('./src/components/reader/SelectionToolbar.vue')['default']
    SessionListSheet: typeof import('./src/components/knowledge-chat/SessionListSheet.vue')['default']
    ShareImportDialog: typeof import('./src/components/ShareImportDialog.vue')['default']
    TocSheet: typeof import('./src/components/TocSheet.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
